// <auto-generated />
using System;
using Lagedra.Modules.JurisdictionPacks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lagedra.Modules.JurisdictionPacks.Migrations
{
    [DbContext(typeof(JurisdictionDbContext))]
    [Migration("20260304181647_AddGapFixesJurisdictionPacks")]
    partial class AddGapFixesJurisdictionPacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jurisdiction")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lagedra.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "jurisdiction");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Aggregates.JurisdictionPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("jurisdiction_packs", "jurisdiction");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.DepositCapRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionCondition")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ExceptionMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JurisdictionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LegalReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("MaxMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "JurisdictionCode");

                    b.ToTable("deposit_cap_rules", "jurisdiction");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.EffectiveDateRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "FieldName")
                        .IsUnique();

                    b.ToTable("effective_date_rules", "jurisdiction");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.EvidenceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MinimumRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("evidence_schedules", "jurisdiction");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.FieldGatingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GatingType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("field_gating_rules", "jurisdiction");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.PackVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecondApproverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("pack_versions", "jurisdiction");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Aggregates.JurisdictionPack", b =>
                {
                    b.OwnsOne("Lagedra.Modules.JurisdictionPacks.Domain.ValueObjects.JurisdictionCode", "JurisdictionCode", b1 =>
                        {
                            b1.Property<Guid>("JurisdictionPackId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("jurisdiction_code");

                            b1.HasKey("JurisdictionPackId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.ToTable("jurisdiction_packs", "jurisdiction");

                            b1.WithOwner()
                                .HasForeignKey("JurisdictionPackId");
                        });

                    b.Navigation("JurisdictionCode")
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.DepositCapRule", b =>
                {
                    b.HasOne("Lagedra.Modules.JurisdictionPacks.Domain.Entities.PackVersion", null)
                        .WithMany("DepositCapRules")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.EffectiveDateRule", b =>
                {
                    b.HasOne("Lagedra.Modules.JurisdictionPacks.Domain.Entities.PackVersion", null)
                        .WithMany("EffectiveDateRules")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.EvidenceSchedule", b =>
                {
                    b.HasOne("Lagedra.Modules.JurisdictionPacks.Domain.Entities.PackVersion", null)
                        .WithMany("EvidenceSchedules")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.FieldGatingRule", b =>
                {
                    b.HasOne("Lagedra.Modules.JurisdictionPacks.Domain.Entities.PackVersion", null)
                        .WithMany("FieldGatingRules")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.PackVersion", b =>
                {
                    b.HasOne("Lagedra.Modules.JurisdictionPacks.Domain.Aggregates.JurisdictionPack", null)
                        .WithMany("Versions")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Aggregates.JurisdictionPack", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Lagedra.Modules.JurisdictionPacks.Domain.Entities.PackVersion", b =>
                {
                    b.Navigation("DepositCapRules");

                    b.Navigation("EffectiveDateRules");

                    b.Navigation("EvidenceSchedules");

                    b.Navigation("FieldGatingRules");
                });
#pragma warning restore 612, 618
        }
    }
}
