import { Link } from "react-router-dom";
import { COMPANY, COMPANY_MAILING_ADDRESS } from "./companyInfo";
import type { LegalDocument } from "./legalTypes";

export const PRIVACY_EFFECTIVE_DATE = "September 3, 2026";

export const privacyDocument: LegalDocument = {
  title: "Privacy Policy",
  metaTitle: "Privacy Policy — Lagedra",
  lede:
    "This Privacy Policy explains how Lagedra collects, uses, shares, and retains personal information when you use the mid-term rental marketplace at lagedra.com. It is written for guests, hosts, property managers, and institutional partners.",
  effectiveDateLabel: PRIVACY_EFFECTIVE_DATE,
  sections: [
    {
      id: "who",
      title: "1. Who we are",
      content: (
        <>
          <p>
            {COMPANY.legalName} operates the mid-term rental marketplace at{" "}
            <a href="https://www.lagedra.com">www.lagedra.com</a>. Brand name:{" "}
            {COMPANY.brand}. Mailing address: {COMPANY_MAILING_ADDRESS}. Support:{" "}
            <a href="mailto:info@lagedra.com">info@lagedra.com</a> or{" "}
            <a href="tel:+12137352362">213-735-2362</a>. More business
            information is on our <Link to="/about">About</Link> page.
          </p>
          <p>
            This policy covers information we process as operator of the
            platform. Hosts, guests, and partners also act independently when
            they message each other or handle a stay. Their practices are not
            controlled by this policy.
          </p>
          <p>
            Our <Link to="/tc">Terms and Conditions</Link> govern use of the
            Services.
          </p>
        </>
      ),
    },
    {
      id: "collect",
      title: "2. Information we collect",
      content: (
        <>
          <p>We collect information in three ways: you provide it, it is generated by use of the Services, or we receive it from others.</p>
          <p>
            <strong>Account and profile.</strong> Name, email, phone, password
            (stored as a hash), role (guest, host, partner, or staff), display
            name, photo, bio, city, languages, and similar profile fields.
            Date of birth is collected when needed to confirm you are 18 or
            older and to complete verification.
          </p>
          <p>
            <strong>Identity and verification.</strong> Government-ID images,
            selfies, and related metadata; verification status; and, if you
            consent, information needed to request a background or consumer
            report. Staff reviewers and identity vendors may see this material
            to complete a check.
          </p>
          <p>
            <strong>Listings and stays.</strong> Listing content, photos,
            precise and approximate location, house rules, lease choice
            (Lagedra template or a document you upload), applications, inquiry
            messages, offers, quotes, Truth Surface records, deal status,
            cancellation events, and compliance or damage-claim files.
          </p>
          <p>
            <strong>Payments.</strong> Billing name, the fact that a payment
            method is on file, charge amounts, payout destination (via Stripe
            Connect), and transaction status. Full card numbers are handled by
            Stripe, not stored on Lagedra.
          </p>
          <p>
            <strong>Partners and channels.</strong> Organization name, member
            and guest records you submit, and listing or reservation data
            imported from a connected channel manager if you authorize that
            connection.
          </p>
          <p>
            <strong>Device and usage.</strong> IP address, browser type,
            approximate location derived from IP, pages viewed, and diagnostic
            logs needed to keep the Services secure and reliable.
          </p>
          <p>
            <strong>Communications.</strong> Emails, in-app notifications,
            support correspondence, and — if you opt in to automated texts —
            your mobile number and SMS consent status, including the contact
            details you use to reach us.
          </p>
        </>
      ),
    },
    {
      id: "use",
      title: "3. How we use information",
      content: (
        <>
          <p>We use personal information to:</p>
          <ul>
            <li>Create and secure accounts, and authenticate sessions.</li>
            <li>
              Operate the marketplace: search, listing review, inquiry,
              booking, sealing deal terms, generating or attaching leases,
              payments, and stay access.
            </li>
            <li>
              Verify identity, prevent fraud and abuse, and apply account
              restrictions when needed.
            </li>
            <li>
              Calculate quotes, deposits, and fees, and to collect amounts you
              authorize.
            </li>
            <li>
              Monitor active stays for compliance signals that the product
              describes, and to run in-platform dispute and evidence flows.
            </li>
            <li>
              Send transactional messages (booking updates, security alerts,
              and phone-verification codes you request) and, with your
              consent, automated SMS campaigns and limited product updates.
            </li>
            <li>
              Improve the Services, diagnose errors, and meet legal, tax, and
              accounting duties.
            </li>
          </ul>
          <p>
            Required platform consents include KYC consent and data-processing
            consent for many write operations. Marketing email is optional.
            FCRA consent is requested only if we order a consumer report.
          </p>
        </>
      ),
    },
    {
      id: "share",
      title: "4. How we share information",
      content: (
        <>
          <p>We share information only as needed to run the Services or as the law requires:</p>
          <ul>
            <li>
              <strong>Other parties to a stay.</strong> After a booking is
              confirmed, we share stay-necessary details with the host, guest,
              and — when involved — the homeowner or placing partner. That
              typically includes names, the precise property address, contact
              information, and the sealed deal terms. Before confirmation, we
              keep the street address and counterpart contact limited.
            </li>
            <li>
              <strong>Payment processors.</strong> Stripe (and its financial
              partners) process charges, payouts, and identity checks required
              for connected accounts.
            </li>
            <li>
              <strong>Identity and screening vendors.</strong> If we use a
              vendor or a consumer-reporting agency, we share the minimum
              needed to complete the check you requested or that a listing
              requires.
            </li>
            <li>
              <strong>Communications and maps.</strong> Email is sent through
              providers such as Twilio SendGrid. Text messages are sent through
              Twilio. Maps and address validation may use Google Maps Platform
              or similar services.
            </li>
            <li>
              <strong>Infrastructure.</strong> Cloud hosting, file storage, and
              security scanning providers that process data on our instructions.
            </li>
            <li>
              <strong>Insurers and protection partners.</strong> When you buy or
              a listing requires a protection product.
            </li>
            <li>
              <strong>Legal and safety.</strong> We may disclose information to
              comply with law, enforce our terms, or protect users, the public,
              or Lagedra from harm.
            </li>
            <li>
              <strong>Business transfers.</strong> Information may transfer if
              we reorganize or sell the business, subject to this policy or a
              successor policy.
            </li>
          </ul>
          <p>
            <strong>We do not sell your personal information</strong> and we do
            not share it for cross-context behavioral advertising. We do not
            let hosts or guests use contact details obtained through Lagedra
            for unrelated marketing.
          </p>
        </>
      ),
    },
    {
      id: "sms",
      title: "5. Text messages (SMS)",
      content: (
        <>
          <p>
            If you opt in at <Link to="/sms">www.lagedra.com/sms</Link> or in
            notification preferences, we use your mobile number to send
            automated texts about booking and payment activity, promotional
            offers, and important account updates. Frequency is up to 8
            messages per month. Message and data rates may apply.
          </p>
          <p>
            Twilio processes those messages as our provider. We store the
            number in E.164 form, whether you are opted in, and when that
            status last changed. Reply <strong>STOP</strong> to cancel,{" "}
            <strong>HELP</strong> for help, or use the same form and
            preferences to opt out. Consent is not required to book a stay or
            to use Lagedra.
          </p>
          <p>
            One-time verification codes are sent only when you ask us to
            verify a number — you add a mobile number, open Verification, and
            tap Send verification code. That request is the opt-in for the
            passcode. Those messages are not campaign texts and are not used
            for marketing. See{" "}
            <Link to="/sms#otp">www.lagedra.com/sms#otp</Link>.
          </p>
          <p>
            See also the <Link to="/tc#sms">Terms — Text messages</Link>.
          </p>
        </>
      ),
    },
    {
      id: "location",
      title: "6. Location and address privacy",
      content: (
        <>
          <p>
            Public listing pages generally show an approximate map area, not a
            precise street pin, until you are a confirmed party to the stay.
            Street address and ZIP are withheld from anonymous and unrelated
            viewers. We still store the precise address so we can generate
            leases, resolve jurisdiction, and reveal access details after
            confirmation.
          </p>
        </>
      ),
    },
    {
      id: "payments-privacy",
      title: "7. Payments",
      content: (
        <>
          <p>
            Checkout and host payouts run on Stripe. Stripe&apos;s privacy
            notice applies to data it processes as an independent controller or
            as our processor, depending on the product. We receive tokens,
            last-four digits or similar descriptors, and transaction outcomes —
            not your full card number.
          </p>
        </>
      ),
    },
    {
      id: "kyc",
      title: "8. Identity documents and sensitive data",
      content: (
        <>
          <p>
            ID photos and selfies are used only to verify who you are, to meet
            anti-fraud and (where applicable) payment-onboarding rules, and to
            complete a review you requested. Access is limited to reviewers and
            vendors with a need to know. We retain this material for as long as
            needed for security, dispute, and legal-retention purposes, then
            delete or de-identify it according to our retention schedule.
          </p>
          <p>
            Do not upload identity documents that are not yours. Uploaded files
            may be scanned for malware.
          </p>
        </>
      ),
    },
    {
      id: "cookies",
      title: "9. Cookies and similar technologies",
      content: (
        <>
          <p>
            We use cookies and similar storage that are necessary to keep you
            signed in, remember preferences, and protect the session. We may
            also use first-party analytics cookies to understand how the
            marketplace is used so we can fix errors and improve features.
          </p>
          <p>
            You can block cookies in your browser. If you block essential
            cookies, sign-in and checkout may not work. We do not use
            third-party advertising networks to track you across unrelated
            sites for ads.
          </p>
        </>
      ),
    },
    {
      id: "retention",
      title: "10. How long we keep information",
      content: (
        <>
          <p>
            We keep account and transaction records for as long as your account
            is active and for a period afterward that is reasonably needed for
            tax, accounting, dispute, insurance, and legal holds. Sealed Truth
            Surface records and lease artifacts for a stay are retained as
            business records of that booking.
          </p>
          <p>
            If you request deletion, we anonymize or delete personal data we
            no longer need, unless a legal hold, an open dispute, an unpaid
            amount, or a law requires us to keep it. Export packages we generate
            for you are stored temporarily and then purged.
          </p>
        </>
      ),
    },
    {
      id: "rights",
      title: "11. Your rights and choices",
      content: (
        <>
          <p>
            Depending on where you live, you may have the right to access,
            correct, delete, or export your personal information, to withdraw
            consent, and to appeal a decision we make about a request.
          </p>
          <p>On Lagedra you can typically:</p>
          <ul>
            <li>Update profile details in your account settings.</li>
            <li>
              Withdraw optional consents (such as marketing or automated SMS
              campaigns). Reply STOP to cancel texts, or use{" "}
              <Link to="/sms">www.lagedra.com/sms</Link>. Withdrawing
              required KYC or data-processing consent may block listing,
              booking, or other write actions until you restore consent or
              close the account.
            </li>
            <li>
              Request a copy of your data or account deletion by emailing{" "}
              <a href="mailto:info@lagedra.com">info@lagedra.com</a>. We may
              need to verify your identity first.
            </li>
          </ul>
          <p>
            <strong>California (CCPA/CPRA).</strong> California residents may
            request to know, delete, or correct personal information and to
            opt out of sale or sharing. We do not sell personal information.
            We will not discriminate against you for exercising these rights.
            Authorized agents may submit a request if they provide proof of
            authority.
          </p>
          <p>
            <strong>European Economic Area, UK, and similar regimes.</strong>{" "}
            If we process your data while you are in these regions, our legal
            bases typically include contract (to provide the Services you
            request), legitimate interests (security, fraud prevention, product
            improvement), consent (optional marketing and certain verification
            steps), and legal obligation. You may lodge a complaint with your
            local supervisory authority.
          </p>
        </>
      ),
    },
    {
      id: "children",
      title: "12. Children",
      content: (
        <>
          <p>
            The Services are for adults. We do not knowingly collect personal
            information from anyone under 18. If you believe a minor created an
            account, contact us and we will close it and delete the data we do
            not need to keep by law.
          </p>
        </>
      ),
    },
    {
      id: "security",
      title: "13. Security",
      content: (
        <>
          <p>
            We use access controls, encryption in transit, hashed passwords,
            staff access limits, and malware scanning on uploads. No method of
            transmission or storage is perfectly secure. You can help by using
            a unique password and telling us if you see unauthorized activity.
          </p>
        </>
      ),
    },
    {
      id: "international",
      title: "14. International users",
      content: (
        <>
          <p>
            We operate the Services from the United States. If you use Lagedra
            from another country, your information will be processed in the
            United States and in other locations where our providers run. Those
            places may have different data-protection laws than your home
            country.
          </p>
        </>
      ),
    },
    {
      id: "changes",
      title: "15. Changes to this policy",
      content: (
        <>
          <p>
            We may update this Privacy Policy. The effective date at the top
            will change when we do. Material changes will be posted on this
            page. If a change requires consent under applicable law, we will
            ask for it.
          </p>
        </>
      ),
    },
    {
      id: "contact",
      title: "16. Contact",
      content: (
        <>
          <p>
            Privacy requests and questions:{" "}
            <a href="mailto:info@lagedra.com">info@lagedra.com</a>
            <br />
            Phone:{" "}
            <a href="tel:+12137352362">213-735-2362</a>
            <br />
            Mail: {COMPANY.legalName}, {COMPANY_MAILING_ADDRESS}
            <br />
            Terms: <Link to="/tc">www.lagedra.com/tc</Link>
          </p>
        </>
      ),
    },
  ],
};
