// <auto-generated />
using System;
using Lagedra.Modules.ListingAndLocation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ListingAndLocation.Migrations
{
    [DbContext(typeof(ListingsDbContext))]
    [Migration("20260225192525_AddListingAttributesAndPolicies")]
    partial class AddListingAttributesAndPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("listings")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lagedra.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("InsuranceRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("JurisdictionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LandlordUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("MaxDepositCents")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyRentCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("SuggestedDepositHighCents")
                        .HasColumnType("bigint");

                    b.Property<long?>("SuggestedDepositLowCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LandlordUserId");

                    b.HasIndex("Status");

                    b.ToTable("listings", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.AmenityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Category", "SortOrder");

                    b.ToTable("amenity_definitions", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingAmenity", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId", "AmenityDefinitionId");

                    b.HasIndex("AmenityDefinitionId");

                    b.ToTable("listing_amenities", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingConsideration", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsiderationDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId", "ConsiderationDefinitionId");

                    b.HasIndex("ConsiderationDefinitionId");

                    b.ToTable("listing_considerations", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingSafetyDevice", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SafetyDeviceDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId", "SafetyDeviceDefinitionId");

                    b.HasIndex("SafetyDeviceDefinitionId");

                    b.ToTable("listing_safety_devices", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.PropertyConsiderationDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("consideration_definitions", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.SafetyDeviceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("safety_device_definitions", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", b =>
                {
                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.Address", "PreciseAddress", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("precise_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("precise_country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("precise_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("precise_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("precise_zip_code");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.CancellationPolicy", "CancellationPolicy", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CustomTerms")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("cancellation_custom_terms");

                            b1.Property<int>("FreeCancellationDays")
                                .HasColumnType("integer")
                                .HasColumnName("cancellation_free_days");

                            b1.Property<int?>("PartialRefundDays")
                                .HasColumnType("integer")
                                .HasColumnName("cancellation_partial_refund_days");

                            b1.Property<int?>("PartialRefundPercent")
                                .HasColumnType("integer")
                                .HasColumnName("cancellation_partial_refund_percent");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("cancellation_policy_type");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.GeoPoint", "ApproxGeoPoint", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("approx_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("approx_longitude");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.HouseRules", "HouseRules", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalRules")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("house_rules_additional_rules");

                            b1.Property<TimeOnly>("CheckInTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_check_in_time");

                            b1.Property<TimeOnly>("CheckOutTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_check_out_time");

                            b1.Property<string>("LeavingInstructions")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("house_rules_leaving_instructions");

                            b1.Property<int>("MaxGuests")
                                .HasColumnType("integer")
                                .HasColumnName("house_rules_max_guests");

                            b1.Property<bool>("PartiesAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("house_rules_parties_allowed");

                            b1.Property<bool>("PetsAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("house_rules_pets_allowed");

                            b1.Property<string>("PetsNotes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("house_rules_pets_notes");

                            b1.Property<TimeOnly?>("QuietHoursEnd")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_quiet_hours_end");

                            b1.Property<TimeOnly?>("QuietHoursStart")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_quiet_hours_start");

                            b1.Property<bool>("SmokingAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("house_rules_smoking_allowed");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.StayRange", "StayRange", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxDays")
                                .HasColumnType("integer")
                                .HasColumnName("stay_max_days");

                            b1.Property<int>("MinDays")
                                .HasColumnType("integer")
                                .HasColumnName("stay_min_days");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("ApproxGeoPoint");

                    b.Navigation("CancellationPolicy");

                    b.Navigation("HouseRules");

                    b.Navigation("PreciseAddress");

                    b.Navigation("StayRange");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingAmenity", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Entities.AmenityDefinition", "AmenityDefinition")
                        .WithMany()
                        .HasForeignKey("AmenityDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("Amenities")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmenityDefinition");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingConsideration", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Entities.PropertyConsiderationDefinition", "ConsiderationDefinition")
                        .WithMany()
                        .HasForeignKey("ConsiderationDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("Considerations")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsiderationDefinition");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingSafetyDevice", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("SafetyDevices")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Entities.SafetyDeviceDefinition", "SafetyDeviceDefinition")
                        .WithMany()
                        .HasForeignKey("SafetyDeviceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SafetyDeviceDefinition");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Considerations");

                    b.Navigation("SafetyDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
