// <auto-generated />
using System;
using Lagedra.Modules.ListingAndLocation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ListingAndLocation.Migrations
{
    [DbContext(typeof(ListingsDbContext))]
    partial class ListingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("listings")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lagedra.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptsPartnerDirectReservations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("AddedVia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("AddedViaDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Bathrooms")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DefaultDepositCents")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DepositBackgroundVerifiedCents")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepositPartnerGuaranteedCents")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepositUnverifiedCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HomeOwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeBrokerClause")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("InstantBookingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JurisdictionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LandlordUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Owner");

                    b.Property<long>("MaxDepositCents")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyRentCents")
                        .HasColumnType("bigint");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SquareFootage")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SubmittedForReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SuggestedDepositHighCents")
                        .HasColumnType("bigint");

                    b.Property<long?>("SuggestedDepositLowCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VirtualTourUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("HomeOwnerUserId");

                    b.HasIndex("LandlordUserId");

                    b.HasIndex("Status");

                    b.ToTable("listings", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.AmenityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Category", "SortOrder");

                    b.ToTable("amenity_definitions", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingAmenity", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId", "AmenityDefinitionId");

                    b.HasIndex("AmenityDefinitionId");

                    b.ToTable("listing_amenities", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingAvailabilityBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DealId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DealId")
                        .HasFilter("\"DealId\" IS NOT NULL");

                    b.HasIndex("ListingId", "CheckInDate", "CheckOutDate");

                    b.ToTable("listing_availability_blocks", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingConsideration", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsiderationDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId", "ConsiderationDefinitionId");

                    b.HasIndex("ConsiderationDefinitionId");

                    b.ToTable("listing_considerations", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "SortOrder");

                    b.ToTable("listing_photos", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<long>("MonthlyRentCents")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("ListingId", "EffectiveFrom");

                    b.ToTable("listing_price_history", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingSafetyDevice", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SafetyDeviceDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId", "SafetyDeviceDefinitionId");

                    b.HasIndex("SafetyDeviceDefinitionId");

                    b.ToTable("listing_safety_devices", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.PropertyConsiderationDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("consideration_definitions", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.SafetyDeviceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("safety_device_definitions", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.SavedListing", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ListingId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("saved_listings", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.SavedListingCollections", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("saved_listing_collections", "listings");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", b =>
                {
                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.Address", "PreciseAddress", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("precise_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("precise_country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("precise_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("precise_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("precise_zip_code");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.CancellationPolicy", "CancellationPolicy", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CustomTerms")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("cancellation_custom_terms");

                            b1.Property<int>("FreeCancellationDays")
                                .HasColumnType("integer")
                                .HasColumnName("cancellation_free_days");

                            b1.Property<int?>("PartialRefundDays")
                                .HasColumnType("integer")
                                .HasColumnName("cancellation_partial_refund_days");

                            b1.Property<int?>("PartialRefundPercent")
                                .HasColumnType("integer")
                                .HasColumnName("cancellation_partial_refund_percent");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("cancellation_policy_type");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.GeoPoint", "ApproxGeoPoint", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("approx_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("approx_longitude");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.HouseRules", "HouseRules", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalRules")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("house_rules_additional_rules");

                            b1.Property<TimeOnly>("CheckInTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_check_in_time");

                            b1.Property<TimeOnly>("CheckOutTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_check_out_time");

                            b1.Property<string>("LeavingInstructions")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("house_rules_leaving_instructions");

                            b1.Property<int>("MaxGuests")
                                .HasColumnType("integer")
                                .HasColumnName("house_rules_max_guests");

                            b1.Property<bool>("PartiesAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("house_rules_parties_allowed");

                            b1.Property<bool>("PetsAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("house_rules_pets_allowed");

                            b1.Property<string>("PetsNotes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("house_rules_pets_notes");

                            b1.Property<TimeOnly?>("QuietHoursEnd")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_quiet_hours_end");

                            b1.Property<TimeOnly?>("QuietHoursStart")
                                .HasColumnType("time without time zone")
                                .HasColumnName("house_rules_quiet_hours_start");

                            b1.Property<bool>("SmokingAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("house_rules_smoking_allowed");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.LeaseTerms", "LeaseTerms", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BuiltBefore1978")
                                .HasColumnType("boolean")
                                .HasColumnName("lease_built_before_1978");

                            b1.Property<int>("EarlyTerminationFeeMonths")
                                .HasColumnType("integer")
                                .HasColumnName("lease_early_termination_fee_months");

                            b1.Property<bool>("Furnished")
                                .HasColumnType("boolean")
                                .HasColumnName("lease_furnished");

                            b1.Property<string>("IncludedAppliancesNotes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("lease_included_appliances");

                            b1.Property<int>("KeyCount")
                                .HasColumnType("integer")
                                .HasColumnName("lease_key_count");

                            b1.Property<long>("KeyReplacementFeeCents")
                                .HasColumnType("bigint")
                                .HasColumnName("lease_key_replacement_fee_cents");

                            b1.Property<int>("LateFeeGraceDays")
                                .HasColumnType("integer")
                                .HasColumnName("lease_late_fee_grace_days");

                            b1.Property<decimal>("LateFeePercent")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("lease_late_fee_percent");

                            b1.Property<string>("LeadPaintKnowledge")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("lease_lead_paint_knowledge");

                            b1.Property<long>("LockoutFeeCents")
                                .HasColumnType("bigint")
                                .HasColumnName("lease_lockout_fee_cents");

                            b1.Property<int>("MailboxKeyCount")
                                .HasColumnType("integer")
                                .HasColumnName("lease_mailbox_key_count");

                            b1.Property<int>("MaxGuestConsecutiveDays")
                                .HasColumnType("integer")
                                .HasColumnName("lease_max_guest_consecutive_days");

                            b1.Property<long>("NsfFirstFeeCents")
                                .HasColumnType("bigint")
                                .HasColumnName("lease_nsf_first_fee_cents");

                            b1.Property<long>("NsfSubsequentFeeCents")
                                .HasColumnType("bigint")
                                .HasColumnName("lease_nsf_subsequent_fee_cents");

                            b1.Property<string>("ParkingDescription")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("lease_parking_description");

                            b1.Property<bool>("ParkingIncludedInRent")
                                .HasColumnType("boolean")
                                .HasColumnName("lease_parking_included_in_rent");

                            b1.Property<int>("ParkingSpaceCount")
                                .HasColumnType("integer")
                                .HasColumnName("lease_parking_space_count");

                            b1.Property<string>("PaymentMethods")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("lease_payment_methods");

                            b1.Property<bool>("RentCapJustCauseExempt")
                                .HasColumnType("boolean")
                                .HasColumnName("lease_rent_cap_just_cause_exempt");

                            b1.Property<int>("RentDueDayOfMonth")
                                .HasColumnType("integer")
                                .HasColumnName("lease_rent_due_day");

                            b1.Property<long>("RentersInsuranceMinLiabilityCents")
                                .HasColumnType("bigint")
                                .HasColumnName("lease_renters_insurance_min_cents");

                            b1.Property<string>("UtilitiesResponsibility")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("lease_utilities_responsibility");

                            b1.Property<bool>("YardMaintenanceByTenant")
                                .HasColumnType("boolean")
                                .HasColumnName("lease_yard_maintenance_by_tenant");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Lagedra.Modules.ListingAndLocation.Domain.ValueObjects.StayRange", "StayRange", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxDays")
                                .HasColumnType("integer")
                                .HasColumnName("stay_max_days");

                            b1.Property<int>("MinDays")
                                .HasColumnType("integer")
                                .HasColumnName("stay_min_days");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings", "listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("ApproxGeoPoint");

                    b.Navigation("CancellationPolicy");

                    b.Navigation("HouseRules");

                    b.Navigation("LeaseTerms");

                    b.Navigation("PreciseAddress");

                    b.Navigation("StayRange");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingAmenity", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Entities.AmenityDefinition", "AmenityDefinition")
                        .WithMany()
                        .HasForeignKey("AmenityDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("Amenities")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmenityDefinition");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingAvailabilityBlock", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("AvailabilityBlocks")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingConsideration", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Entities.PropertyConsiderationDefinition", "ConsiderationDefinition")
                        .WithMany()
                        .HasForeignKey("ConsiderationDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("Considerations")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsiderationDefinition");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingPhoto", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("Photos")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Entities.ListingSafetyDevice", b =>
                {
                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", null)
                        .WithMany("SafetyDevices")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lagedra.Modules.ListingAndLocation.Domain.Entities.SafetyDeviceDefinition", "SafetyDeviceDefinition")
                        .WithMany()
                        .HasForeignKey("SafetyDeviceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SafetyDeviceDefinition");
                });

            modelBuilder.Entity("Lagedra.Modules.ListingAndLocation.Domain.Aggregates.Listing", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("AvailabilityBlocks");

                    b.Navigation("Considerations");

                    b.Navigation("Photos");

                    b.Navigation("SafetyDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
