namespace Lagedra.Auth.Presentation.Contracts;

public sealed record UpdateProfileRequest(
    string? FirstName,
    string? LastName,
    string? DisplayName,
    string? PhoneNumber,
    string? Bio,
    Uri? ProfilePhotoUrl,
    string? City,
    string? State,
    string? Country,
    string? Languages,
    string? Occupation,
    DateOnly? DateOfBirth,
    string? EmergencyContactName,
    string? EmergencyContactPhone,
    string? MailingStreet = null,
    string? MailingCity = null,
    string? MailingState = null,
    string? MailingZip = null,
    string? MailingCountry = null,
    bool? NoticeAddressSameAsMailing = null,
    string? NoticeStreet = null,
    string? NoticeCity = null,
    string? NoticeState = null,
    string? NoticeZip = null,
    string? NoticeCountry = null,
    string? BrokerName = null,
    string? BrokerDreLicense = null,
    string? BrokerScopeNotes = null);
