namespace Lagedra.Modules.ListingAndLocation.Presentation.Contracts;

using Lagedra.Modules.ListingAndLocation.Domain.Enums;

public sealed record UpdateListingRequest(
    PropertyType PropertyType,
    string Title,
    string Description,
    long MonthlyRentCents,
    int Bedrooms,
    decimal Bathrooms,
    int MinStayDays,
    int MaxStayDays,
    long MaxDepositCents,
    int? SquareFootage = null,
    HouseRulesRequest? HouseRules = null,
    CancellationPolicyRequest? CancellationPolicy = null,
    IReadOnlyList<Guid>? AmenityIds = null,
    IReadOnlyList<Guid>? SafetyDeviceIds = null,
    IReadOnlyList<Guid>? ConsiderationIds = null,
    bool? InstantBookingEnabled = null,
    Uri? VirtualTourUrl = null,
    long? DefaultDepositCents = null,
    bool ClearDefaultDeposit = false,
    long? DepositUnverifiedCents = null,
    long? DepositBackgroundVerifiedCents = null,
    long? DepositPartnerGuaranteedCents = null,
    LeaseTermsRequest? LeaseTerms = null,
    ListingManagerRole ManagerRole = ListingManagerRole.Owner,
    Guid? HomeOwnerUserId = null,
    string? HomeOwnerEmail = null,
    bool IncludeBrokerClause = false);

public sealed record LeaseTermsRequest(
    int RentDueDayOfMonth = 1,
    long NsfFirstFeeCents = 2500,
    long NsfSubsequentFeeCents = 3500,
    decimal LateFeePercent = 5m,
    int LateFeeGraceDays = 3,
    string? UtilitiesResponsibility = null,
    bool YardMaintenanceByTenant = false,
    bool Furnished = false,
    string? IncludedAppliancesNotes = null,
    int KeyCount = 1,
    int MailboxKeyCount = 0,
    long KeyReplacementFeeCents = 20000,
    long LockoutFeeCents = 20000,
    int ParkingSpaceCount = 0,
    string? ParkingDescription = null,
    bool ParkingIncludedInRent = true,
    int MaxGuestConsecutiveDays = 7,
    long RentersInsuranceMinLiabilityCents = 100_000_00,
    int EarlyTerminationFeeMonths = 2,
    bool BuiltBefore1978 = false,
    string? LeadPaintKnowledge = null,
    bool RentCapJustCauseExempt = false,
    string? PaymentMethods = null);
