export const endpoints = {
  auth: {
    register: "/v1/auth/register",
    verifyEmail: "/v1/auth/verify-email",
    resendVerification: "/v1/auth/resend-verification",
    login: "/v1/auth/login",
    externalLogin: "/v1/auth/external-login",
    refresh: "/v1/auth/refresh",
    logout: "/v1/auth/logout",
    forgotPassword: "/v1/auth/forgot-password",
    resetPassword: "/v1/auth/reset-password",
    changePassword: "/v1/auth/change-password",
    me: "/v1/auth/me",
    users: "/v1/auth/users",
    userRole: (userId: string) => `/v1/auth/users/${userId}/role`,
  },
  listings: {
    search: "/v1/listings",
    mine: "/v1/listings/mine",
    detail: (id: string) => `/v1/listings/${id}`,
    similar: (id: string) => `/v1/listings/${id}/similar`,
    shareUrl: (id: string) => `/v1/listings/${id}/share-url`,
    priceHistory: (id: string) => `/v1/listings/${id}/price-history`,
    availability: (id: string) => `/v1/listings/${id}/availability`,
    publish: (id: string) => `/v1/listings/${id}/publish`,
    close: (id: string) => `/v1/listings/${id}/close`,
    approxLocation: (id: string) => `/v1/listings/${id}/approx-location`,
    lockAddress: (id: string) => `/v1/listings/${id}/lock-address`,
    addPhoto: (id: string) => `/v1/listings/${id}/photos`,
    photo: (listingId: string, photoId: string) => `/v1/listings/${listingId}/photos/${photoId}`,
    coverPhoto: (listingId: string, photoId: string) =>
      `/v1/listings/${listingId}/photos/${photoId}/cover`,
    reorderPhotos: (id: string) => `/v1/listings/${id}/photos/reorder`,
    blockDates: (id: string) => `/v1/listings/${id}/block-dates`,
    unblockDates: (id: string, blockId: string) =>
      `/v1/listings/${id}/block-dates/${blockId}`,
  },
  savedListings: {
    save: (listingId: string) => `/v1/saved-listings/${listingId}`,
    list: "/v1/saved-listings",
    collections: "/v1/saved-listings/collections",
    collection: (collectionId: string) => `/v1/saved-listings/collections/${collectionId}`,
    addToCollection: (listingId: string, collectionId: string) =>
      `/v1/saved-listings/${listingId}/collections/${collectionId}`,
    removeFromCollection: (listingId: string) => `/v1/saved-listings/${listingId}/collections`,
  },
  definitions: {
    amenities: "/v1/listing-definitions/amenities",
    safetyDevices: "/v1/listing-definitions/safety-devices",
    considerations: "/v1/listing-definitions/considerations",
  },
  applications: {
    submit: "/v1/applications",
    mine: "/v1/applications/mine",
    detail: (id: string) => `/v1/applications/${id}`,
    approve: (id: string) => `/v1/applications/${id}/approve`,
    reject: (id: string) => `/v1/applications/${id}/reject`,
    forListing: (listingId: string) => `/v1/applications/listing/${listingId}`,
  },
  adminDefinitions: {
    amenities: "/v1/admin/listing-definitions/amenities",
    amenity: (id: string) => `/v1/admin/listing-definitions/amenities/${id}`,
    safetyDevices: "/v1/admin/listing-definitions/safety-devices",
    safetyDevice: (id: string) => `/v1/admin/listing-definitions/safety-devices/${id}`,
    considerations: "/v1/admin/listing-definitions/considerations",
    consideration: (id: string) => `/v1/admin/listing-definitions/considerations/${id}`,
  },
  privacy: {
    recordConsent: "/v1/privacy/consent",
    userConsents: (userId: string) => `/v1/privacy/consents/${userId}`,
  },
} as const;
