// <auto-generated />
using System;
using Lagedra.Infrastructure.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lagedra.Infrastructure.Migrations
{
    [DbContext(typeof(PlatformSettingsDbContext))]
    [Migration("20260304192240_AddPaymentAndDamageClaimSettings")]
    partial class AddPaymentAndDamageClaimSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lagedra.SharedKernel.Settings.PlatformSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Key");

                    b.ToTable("platform_settings", "platform");

                    b.HasData(
                        new
                        {
                            Key = "protocol_fee.monthly_cents",
                            Description = "Monthly protocol fee per active deal in cents (paid by host)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "7900"
                        },
                        new
                        {
                            Key = "protocol_fee.pilot_discount_cents",
                            Description = "Pilot discount in cents subtracted from protocol fee",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3900"
                        },
                        new
                        {
                            Key = "protocol_fee.pilot_active",
                            Description = "Whether the pilot discount is currently active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "arbitration_fee.protocol_adjudication_cents",
                            Description = "Protocol adjudication filing fee in cents",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "4900"
                        },
                        new
                        {
                            Key = "arbitration_fee.binding_arbitration_cents",
                            Description = "Binding arbitration filing fee in cents",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "9900"
                        },
                        new
                        {
                            Key = "payment.grace_period_days",
                            Description = "Days after booking confirmation before payment is considered overdue",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Key = "payment.reminder_after_days",
                            Description = "Days after booking confirmation to send payment reminder to tenant",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "4"
                        },
                        new
                        {
                            Key = "payment.auto_cancel_after_days",
                            Description = "Days after booking confirmation to auto-cancel if tenant has not paid",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "7"
                        },
                        new
                        {
                            Key = "host_platform_payment.reminder_interval_days",
                            Description = "Days between reminder emails to host for unpaid platform fees",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "2"
                        },
                        new
                        {
                            Key = "host_platform_payment.suspend_after_days",
                            Description = "Days after host confirms tenant payment to suspend host if platform fee not paid",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "14"
                        },
                        new
                        {
                            Key = "cancellation.insurance_refund_deadline_days",
                            Description = "Days after cancellation within which insurance premium refund is eligible",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Key = "damage_claim.filing_deadline_days",
                            Description = "Days after check-out within which a damage claim can be filed",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "14"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
